### ISSUE TITLE
Not working at all?

### ISSUE THREAD

**Issue by TheFlashBold** [Majestcx/OpenLoad-Downloader#1]
Input: # hhvm openload.co "5kZgoN5_Cyc"
Output: {"error":0,"msg":"Server error"}

HHVM Verison: HipHop VM 3.14.4 (rel) equivalent to PHP 7

openload.co content:
#!/usr/bin/hhvm
<?php
require "composer/vendor/autoload.php";
use JonnyW\PhantomJs\Client;

$video = $argv[1];
if($video == ''){
        echo "Where is the media ID?"; //https://openload.co/embed/7zLUwKrlQqCk  (The ID is "7zLUwKrlQqCk" in this case)
        exit();
}else{
        $client = Client::getInstance();
        $client->getEngine()->setPath('/usr/local/bin/phantomjs');
        if(strpos($video, '.') !== False){
                $video = explode('.', $video)[0];
        }
        $request = $client->getMessageFactory()->createRequest("https://openload.co/embed/$video", 'GET');
        $response = $client->getMessageFactory()->createResponse();
        $client->send($request, $response);
        if($response->getStatus() === 200) {
                $openload = $response->getContent();
                if(strpos($openload, 'We are sorry!') !== False){
                        echo json_encode(array('error' => '404', 'msg' => 'File not found'));
                        exit();
                }
                $openload = explode('<span id="streamurl">', $openload)[1];
                $file = 'https://openload.co/stream/'.explode('</span>', $openload)[0].'?mime=true';
                $headers = get_headers($file,1);

                //Final Args
                $filename = explode('?', end(explode('/',$headers['Location'])))[0];
                $file = explode('?', $headers['Location'])[0];
                $size = $headers['Content-Length'];

                //Download Code
                set_time_limit(0);
                header('Content-Type: video/mp4');
                header('Content-Length: '.$size);

                $f = fopen($file, "rb");
                while (!feof($f)) {
                        echo fread($f, 8*1024);
                        flush();
                        ob_flush();
                }
                exit();
        }else{
                echo json_encode(array('error' => $response->getStatus(), 'msg' => 'Server error'));
                exit();
        }
}

Edit:
It seems like i aways get wrong responces from openload with phantomjs. If i download the page with wget i get content.

**Comment by Majestcx** [comment]
I test it on https://opendownload.herokuapp.com/video/XTk9RhezBbM and it runs...

**Comment by Majestcx** [comment]
I never used HHVM.

**Comment by Majestcx** [comment]
I used PhantomJS because wget don't download JavaScript edited page.

**Comment by TheFlashBold** [comment]
I know that ^^, Openload loads the stream link with javascript. I tried to understand the script, but they are obfuscated.

**Comment by TheFlashBold** [comment]
How do you install this with composer?

**Comment by TheFlashBold** [comment]
see for your self https://soos.li/video/?id=XTk9RhezBbM

**Comment by Majestcx** [comment]
Heroku install automatically it if the git contains the right composer.lock and .json, Ii fact, I added them on purpose to facilitate the work if you used heroku too ^^

**Comment by TheFlashBold** [comment]
This sucks :(

**Comment by TheFlashBold** [comment]
No help then?

**Comment by Majestcx** [comment]
If you use you own vps for the site, you could install composer and run this script, otherwise I'm sorry, but I do not know how to do but use heroku or similar.

**Comment by TheFlashBold** [comment]
i have a root server and i use composer, but i don't understand the use of composer

**Comment by TheFlashBold** [comment]
Does the heroku version run for ever? or how long will it? can i use it?

**Comment by Majestcx** [comment]
Heroku runs forever, the only "problem" is that the application goes into standby if not used for more than 30 minutes. So to load the page after standby takes a minimum extra.

**Comment by ytkingo** [comment]
hello i need videomega.tv player for 50$

if u can contact me: ytkingo@gmail.com
